[platformio]
default_envs =
  entry_io
  entry_io_debug
  actuators
  leds_zone_a
  leds_zone_b

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.3
  miguelbalboa/MFRC522 @ ^1.4.10
  madhephaestus/ESP32Servo @ ^3.0.5
  marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=1

[env:entry_io]
build_src_filter = +<common/> +<entry_io/> -<exit/> -<entry/> -<zone/> -<actuators/> -<leds/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_ENTRY_IO
  -D POLARIS_DEVICE_ID=\"entry-io-01\"
  -D POLARIS_DEVICE_CONFIG_HEADER=\"polaris_device.entry_io.h\"
  -D POLARIS_ENTRY_SERVO_ID=\"entry-servo\"
  -D POLARIS_ENTRY_DISPLAY_ID=\"entry-lcd\"
  -D POLARIS_EXIT_SERVO_ID=\"exit-servo\"

[env:entry_io_debug]
extends = env:entry_io
build_flags =
  ${env:entry_io.build_flags}
  -D POLARIS_DEBUG_ULTRASONIC

[env:actuators]
build_src_filter = +<common/> +<actuators/> -<exit/> -<entry/> -<zone/> -<entry_io/> -<leds/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_ACTUATORS
  -D POLARIS_DEVICE_ID=\"actuators-01\"
  -D POLARIS_DEVICE_CONFIG_HEADER=\"polaris_device.actuators.h\"
  -D POLARIS_ENTRY_SERVO_ID=\"entry-servo\"
  -D POLARIS_EXIT_SERVO_ID=\"exit-servo\"
  -D POLARIS_SERVO_INVERT=1

[env:leds_zone_a]
build_src_filter = +<common/> +<leds/> -<entry/> -<exit/> -<zone/> -<entry_io/> -<actuators/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_LEDS
  -D POLARIS_DEVICE_ID=\"leds-zone-a\"
  -D POLARIS_DEVICE_CONFIG_HEADER=\"polaris_device.leds_zone_a.h\"
  -D POLARIS_SPOT_FIRST=1
  -D POLARIS_SPOT_LAST=5

[env:leds_zone_b]
build_src_filter = +<common/> +<leds/> -<entry/> -<exit/> -<zone/> -<entry_io/> -<actuators/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_LEDS
  -D POLARIS_DEVICE_ID=\"leds-zone-b\"
  -D POLARIS_DEVICE_CONFIG_HEADER=\"polaris_device.leds_zone_b.h\"
  -D POLARIS_SPOT_FIRST=6
  -D POLARIS_SPOT_LAST=10
