; Polaris ESP32 — Fase 10.3
; Docs: docs/flujos.md · Pines: include/pins_*.h

[platformio]
default_envs = entry

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.3
  miguelbalboa/MFRC522 @ ^1.4.10
  madhephaestus/ESP32Servo @ ^3.0.5
  marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=1

[env:entry]
build_src_filter = +<common/> +<entry/> -<exit/> -<zone/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_ENTRY
  -D POLARIS_DEVICE_ID=\"entry-gate-01\"
  -D POLARIS_ENTRY_SERVO_ID=\"entry-servo\"
  -D POLARIS_ENTRY_DISPLAY_ID=\"entry-lcd\"

[env:exit]
build_src_filter = +<common/> +<exit/> -<entry/> -<zone/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_EXIT
  -D POLARIS_DEVICE_ID=\"exit-gate-01\"
  -D POLARIS_EXIT_SERVO_ID=\"exit-servo\"

[env:zone_a]
build_src_filter = +<common/> +<zone/> -<entry/> -<exit/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_ZONE
  -D POLARIS_DEVICE_ID=\"spots-zone-a\"
  -D POLARIS_SPOT_FIRST=1
  -D POLARIS_SPOT_LAST=4

[env:zone_b]
build_src_filter = +<common/> +<zone/> -<entry/> -<exit/>
build_flags =
  ${env.build_flags}
  -D POLARIS_ROLE_ZONE
  -D POLARIS_DEVICE_ID=\"spots-zone-b\"
  -D POLARIS_SPOT_FIRST=7
  -D POLARIS_SPOT_LAST=10
