dev:
  - 'iac/environments/dev/**'
  - 'iac/modules/**'
  - 'iac/bootstrap/**'
  - 'atlantis.yaml'

staging:
  - 'iac/environments/staging/**'
  - 'iac/modules/**'
  - 'iac/bootstrap/**'
  - 'atlantis.yaml'

prod:
  - 'iac/environments/prod/**'
  - 'iac/modules/**'
  - 'iac/bootstrap/**'
  - 'atlantis.yaml'
